/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as ModelRouteImport } from './routes/model'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AirportsRouteImport } from './routes/airports'
import { Route as AirlinesRouteImport } from './routes/airlines'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsRoute = AirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const AirlinesRoute = AirlinesRouteImport.update({
  id: '/airlines',
  path: '/airlines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airlines': typeof AirlinesRoute
  '/airports': typeof AirportsRoute
  '/compare': typeof CompareRoute
  '/model': typeof ModelRoute
  '/predictor': typeof PredictorRoute
  '/recommend': typeof RecommendRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airlines': typeof AirlinesRoute
  '/airports': typeof AirportsRoute
  '/compare': typeof CompareRoute
  '/model': typeof ModelRoute
  '/predictor': typeof PredictorRoute
  '/recommend': typeof RecommendRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airlines': typeof AirlinesRoute
  '/airports': typeof AirportsRoute
  '/compare': typeof CompareRoute
  '/model': typeof ModelRoute
  '/predictor': typeof PredictorRoute
  '/recommend': typeof RecommendRoute
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airlines'
    | '/airports'
    | '/compare'
    | '/model'
    | '/predictor'
    | '/recommend'
    | '/routes'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airlines'
    | '/airports'
    | '/compare'
    | '/model'
    | '/predictor'
    | '/recommend'
    | '/routes'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/airlines'
    | '/airports'
    | '/compare'
    | '/model'
    | '/predictor'
    | '/recommend'
    | '/routes'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirlinesRoute: typeof AirlinesRoute
  AirportsRoute: typeof AirportsRoute
  CompareRoute: typeof CompareRoute
  ModelRoute: typeof ModelRoute
  PredictorRoute: typeof PredictorRoute
  RecommendRoute: typeof RecommendRoute
  RoutesRoute: typeof RoutesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports': {
      id: '/airports'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airlines': {
      id: '/airlines'
      path: '/airlines'
      fullPath: '/airlines'
      preLoaderRoute: typeof AirlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirlinesRoute: AirlinesRoute,
  AirportsRoute: AirportsRoute,
  CompareRoute: CompareRoute,
  ModelRoute: ModelRoute,
  PredictorRoute: PredictorRoute,
  RecommendRoute: RecommendRoute,
  RoutesRoute: RoutesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
